# Generated by Django 4.1.7 on 2023-05-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_category_users_dob_users_education_users_exp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='exp',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='dob',
        ),
        migrations.AddField(
            model_name='users',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
