# Generated by Django 3.2.18 on 2023-05-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_exp_users_age_remove_users_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='applied_jobs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='created_jobs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
