# Generated by Django 4.1.5 on 2023-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('expected_payment', models.PositiveIntegerField()),
            ],
        ),
    ]
