# Generated by Django 4.1.2 on 2023-02-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_category", models.CharField(max_length=255)),
                ("icon_url", models.TextField()),
            ],
        ),
    ]
