# Generated by Django 4.1.2 on 2023-02-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255)),
                ("phone", models.BigIntegerField()),
                ("rating", models.FloatField()),
                ("location", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
            ],
        ),
    ]
