# Generated by Django 3.1 on 2023-05-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pay', models.PositiveIntegerField()),
                ('required_skills', models.TextField()),
                ('status', models.CharField(choices=[('Hiring', 'Hiring'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Payment', 'Payment'), ('Complete', 'Complete')], max_length=255)),
                ('category', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='users.users')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='users.users', to_field='email')),
            ],
        ),
    ]
