# Generated by Django 4.1.2 on 2023-02-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employer", "0001_initial"),
        ("service_provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("pay", models.PositiveIntegerField()),
                ("required_skills", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Hiring", "Hiring"),
                            ("In Progress", "In Progress"),
                            ("Done", "Done"),
                            ("Payment", "Payment"),
                            ("Complete", "Complete"),
                        ],
                        default="Hiring",
                        max_length=255,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employer.employer",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service_provider.service_provider",
                    ),
                ),
            ],
        ),
    ]
