# Generated by Django 4.1.7 on 2023-02-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
        ('job', '0002_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_provider.service_provider'),
        ),
    ]
