# Generated by Django 4.1.7 on 2023-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20230316_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Hiring', 'Hiring'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Payment', 'Payment'), ('Complete', 'Complete')], max_length=255),
        ),
    ]
