# Generated by Django 4.1.7 on 2023-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
